name: deployment
on:
    push:
        branches:
            - main
            - frontend/proof-of-concept

jobs:
    deploy:
        name: Deploy website
        runs-on: ubuntu-latest
        steps:
            - name: Install ssh keys
              run: |
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                ssh-keyscan -H aldenluth.fi > ~/.ssh/known_hosts
            - name: Connect and deploy
              run: ssh root@aldenluth.fi "cd trackorder && git pull --ff-only && ./gradlew build && docker compose up -d --build && docker system prune -a -f"
            - name: Cleanup
              run: rm -rf ~/.ssh